# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push

jobs:

  build:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v3

      - name: cmake
        run: |
          cmake -G "Visual Studio 17 2022" -A Win32 -S . -B "build-win32"
      
      - name: build
        run: |
          cmake --build build-win32 --config Release